### ISSUE TITLE
Grid will not work

### ISSUE THREAD

**Issue by goug0035** [goug0035/marygough.ca#1]
My grid is really not working and I do not know why my classes are not working.

@ericadamski
@thomasjbradley

<main>
    <div class="grid">
      <div class="unit island unit-l-1-3 unit-m-1-3 unit-s-1">
        <img class="" src="http://placehold.it/150x150">
      </div>
      <div class="unit island unit-l-1-3 unit-m-1-3 unit-s-1">
        <img src="http://placehold.it/150x150">
      </div>
      <div class="unit island unit-l-1-3 unit-m-1-3 unit-s-1">
        <img src="http://placehold.it/150x150">
      </div>
    </div>
</main>

**Comment by ericadamski** [comment]
What `html` page is that on @goug0035 ?

We can discuss this in class tonight.

**Comment by goug0035** [comment]
This is the design page. I would like to have 3 sketched/rough images, then text under, then a final span image.

**Comment by ericadamski** [comment]
@goug0035 the grid code looks ok, I will take more of a look in class.
