### ISSUE TITLE
website not updating

### ISSUE THREAD

**Issue by goug0035** [goug0035/marygough.ca#2]
@ericadamski

I updated and added all the detail for friday and it worked but when i went to look at my site today, all the details i added in my last commit don't show on the site. weird thing is that the commit still shows on github

**Comment by ericadamski** [comment]
@goug0035 can you check to make sure that your settings for your website are pointed to the correct branch? It would be in this section in the settings of your git repo.

![screen shot 2016-11-22 at 11 42 11 am](https://cloud.githubusercontent.com/assets/6516758/20532641/be9c48b6-b0a8-11e6-9861-01926ae43359.png)

**Comment by goug0035** [comment]
Thank you that worked :)
